# Generated by Django 6.0.3 on 2026-04-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('port', models.IntegerField(default=8728)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
