# Generated by Django 6.0.3 on 2026-04-23 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_automationrunlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=50)),
                ('mac_address', models.CharField(blank=True, max_length=20)),
                ('server', models.CharField(blank=True, max_length=50)),
                ('uptime', models.CharField(blank=True, max_length=50)),
                ('bytes_in', models.BigIntegerField(default=0)),
                ('bytes_out', models.BigIntegerField(default=0)),
                ('session_type', models.CharField(default='hotspot', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_file', models.CharField(max_length=255)),
                ('export_file', models.CharField(blank=True, max_length=255)),
                ('backup_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('file_size', models.BigIntegerField(default=0)),
                ('duration', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-backup_time'],
            },
        ),
        migrations.CreateModel(
            name='FailoverEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_wan', models.CharField(blank=True, max_length=20)),
                ('new_wan', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=30)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'dashboard_failoverevent',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FailoverState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_wan', models.CharField(default='ISP1_ACTIVE', max_length=20)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboard_failoverstate',
            },
        ),
        migrations.CreateModel(
            name='InterfaceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(default='DOWN', max_length=10)),
                ('tx_bytes', models.BigIntegerField(default=0)),
                ('rx_bytes', models.BigIntegerField(default=0)),
                ('tx_rate', models.FloatField(default=0)),
                ('rx_rate', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MonitorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_data', models.JSONField(default=dict)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboard_monitorstate',
            },
        ),
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interface_name', models.CharField(max_length=50)),
                ('tx_bytes_total', models.BigIntegerField(default=0)),
                ('rx_bytes_total', models.BigIntegerField(default=0)),
                ('tx_rate_mbps', models.FloatField(default=0)),
                ('rx_rate_mbps', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PPPoEUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('profile', models.CharField(default='default', max_length=50)),
                ('service', models.CharField(default='pppoe', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dashboard_pppoeuser',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QoSEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=20)),
                ('rx_mbps', models.FloatField(default=0)),
                ('tx_mbps', models.FloatField(default=0)),
                ('queue_name', models.CharField(blank=True, max_length=50)),
                ('limit_applied', models.CharField(blank=True, max_length=20)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'dashboard_qosevent',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QoSState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_throttled', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboard_qosstate',
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('failure_count', models.IntegerField(default=0)),
                ('action', models.CharField(max_length=20)),
                ('ban_duration', models.CharField(default='1d', max_length=20)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'dashboard_securityevent',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SpeedtestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_time', models.DateTimeField(auto_now_add=True)),
                ('ping', models.FloatField(default=0)),
                ('download', models.FloatField(default=0)),
                ('upload', models.FloatField(default=0)),
                ('server_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'dashboard_speedtestlog',
                'ordering': ['-test_time'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert_type', models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger'), ('info', 'Info')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_load', models.IntegerField(default=0)),
                ('ram_usage', models.IntegerField(default=0)),
                ('free_memory_mb', models.IntegerField(default=0)),
                ('total_memory_mb', models.IntegerField(default=0)),
                ('uptime', models.CharField(blank=True, max_length=50)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('board_name', models.CharField(blank=True, max_length=100)),
                ('internet_status', models.CharField(default='DOWN', max_length=10)),
                ('ping_latency', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('banned_ips', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrackedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(db_index=True, max_length=20)),
                ('hostname', models.CharField(default='Unknown Device', max_length=200)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dashboard_trackeddevice',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='VoucherUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=20)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('mac_address', models.CharField(blank=True, max_length=20)),
                ('session_duration', models.IntegerField(default=0)),
                ('bytes_used', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='dashboard_a_activit_37f6ee_idx',
            old_name='dashboard_a_activit_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='dashboard_a_router__d32b40_idx',
            old_name='dashboard_a_router_idx',
        ),
        migrations.RenameIndex(
            model_name='automationrunlog',
            new_name='dashboard_a_task_na_8684e2_idx',
            old_name='dashboard_a_task_na_6eb543_idx',
        ),
        migrations.RenameIndex(
            model_name='automationrunlog',
            new_name='dashboard_a_status_a24397_idx',
            old_name='dashboard_a_status_8bb9b8_idx',
        ),
        migrations.AddField(
            model_name='router',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('voucher_generate', 'Voucher Generation'), ('voucher_delete', 'Voucher Deletion'), ('voucher_batch_delete', 'Batch Voucher Deletion'), ('user_kick', 'User Kick'), ('router_add', 'Router Added'), ('router_delete', 'Router Deleted'), ('router_switch', 'Router Switched'), ('system_reboot', 'System Reboot'), ('system_reset', 'System Reset'), ('backup_manual', 'Manual Backup'), ('backup_auto', 'Auto Backup'), ('login', 'User Login'), ('logout', 'User Logout'), ('speedtest', 'Speedtest'), ('device_detected', 'New Device Detected'), ('failover', 'WAN Failover'), ('security_ban', 'Security Ban'), ('qos_change', 'QoS Change')], max_length=30),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='profile',
            field=models.CharField(choices=[('1jam', '1 Jam'), ('3jam', '3 Jam'), ('1hari', '1 Hari'), ('1minggu', '1 Minggu'), ('custom', 'Custom')], default='1jam', max_length=20),
        ),
        migrations.AddField(
            model_name='activeuser',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.router'),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.router'),
        ),
        migrations.AddField(
            model_name='failoverevent',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.router'),
        ),
        migrations.AddField(
            model_name='failoverstate',
            name='router',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='failover_state', to='dashboard.router'),
        ),
        migrations.AddField(
            model_name='interfacemetrics',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.router'),
        ),
        migrations.AddField(
            model_name='monitorstate',
            name='router',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_state', to='dashboard.router'),
        ),
        migrations.AddField(
            model_name='networktraffic',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.router'),
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.router'),
        ),
        migrations.AddField(
            model_name='qosevent',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.router'),
        ),
        migrations.AddField(
            model_name='qosstate',
            name='router',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qos_state', to='dashboard.router'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.router'),
        ),
        migrations.AddField(
            model_name='speedtestlog',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.router'),
        ),
        migrations.AddField(
            model_name='systemalert',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.router'),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.router'),
        ),
        migrations.AddField(
            model_name='interfacemetrics',
            name='system_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.systemmetrics'),
        ),
        migrations.AddField(
            model_name='trackeddevice',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.router'),
        ),
        migrations.AddField(
            model_name='voucherusage',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.router'),
        ),
        migrations.AddField(
            model_name='voucherusage',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.voucher'),
        ),
        migrations.AddIndex(
            model_name='activeuser',
            index=models.Index(fields=['router', 'username', '-timestamp'], name='dashboard_a_router__d535c3_idx'),
        ),
        migrations.AddIndex(
            model_name='networktraffic',
            index=models.Index(fields=['router', 'interface_name', '-timestamp'], name='dashboard_n_router__13df0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pppoeuser',
            unique_together={('router', 'username')},
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['router', '-timestamp'], name='dashboard_s_router__54f770_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trackeddevice',
            unique_together={('router', 'mac_address')},
        ),
    ]
