# Generated by Django 6.0.3 on 2026-04-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_activeuser_backuplog_failoverevent_failoverstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='bandwidth',
            field=models.CharField(default='Unlimited', max_length=20),
        ),
    ]
